import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {demoCar} from './demo';
import type {Car} from './types';
export type Runtime={DB:D1Database;BUCKET:R2Bucket;ADMIN_EMAILS?:string;ANTHROPIC_API_KEY?:string;ANTHROPIC_MODEL?:string};
export const runtime=()=>env as unknown as Runtime;
export async function adminUser(){const user=await getChatGPTUser();const allowed=(runtime().ADMIN_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);return user&&allowed.includes(user.email.toLowerCase())?user:null}
export async function guard(req?:Request){if(!await adminUser())throw new HttpError(403,'U hebt geen toegang tot het beheer. Meld u aan met een toegelaten account.');if(req&&req.method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'Deze aanvraag komt niet van onze website.')} }
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function fail(e:unknown){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});console.error('Request failed',e instanceof Error?e.message:'unknown');return Response.json({error:'Dit lukt momenteel niet. Uw invoer blijft behouden. Probeer opnieuw.'},{status:500})}
export async function jsonBody(req:Request){if(!req.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Verwacht een JSON-aanvraag.');const text=await req.text();if(text.length>60000)throw new HttpError(413,'Te veel tekst.');try{return JSON.parse(text)}catch{throw new HttpError(400,'Ongeldige invoer.')}}
export async function seed(){const db=runtime().DB;if(!db)throw new Error('Database unavailable');await db.prepare('INSERT OR IGNORE INTO cars (id,slug,status,data,updated_at) VALUES (?,?,?,?,?)').bind(demoCar.id,demoCar.slug,demoCar.status,JSON.stringify(demoCar),demoCar.updatedAt).run()}
export async function listCars(admin=false):Promise<Car[]>{await seed();const {results}=await runtime().DB.prepare(admin?"SELECT data,status,updated_at FROM cars WHERE status != 'archived' ORDER BY updated_at DESC":"SELECT data,status,updated_at FROM cars WHERE status IN ('published','sold') ORDER BY updated_at DESC").all<{data:string,status:Car['status'],updated_at:string}>();return results.map(r=>({...JSON.parse(r.data),status:r.status,updatedAt:r.updated_at,translations:JSON.parse(r.data).translations||(JSON.parse(r.data).demo?demoCar.translations:undefined)}))}
export async function getCar(key:string,admin=false):Promise<Car|null>{await seed();const row=await runtime().DB.prepare('SELECT data,status,updated_at FROM cars WHERE (slug=? OR id=?) AND status != ?').bind(key,key,'archived').first<{data:string,status:Car['status'],updated_at:string}>();if(!row||(!admin&&row.status==='draft'))return null;return {...JSON.parse(row.data),status:row.status,updatedAt:row.updated_at,translations:JSON.parse(row.data).translations||(JSON.parse(row.data).demo?demoCar.translations:undefined)}}
